matrix:
  # This causes the build to complete immediately upon first failure or once
  # required jobs are green.
  fast_finish: true

  # Building APK/IPA takes a long time; do not wait for them to finish.
  #  allow_failures:
  #  - env: JOB=APK
  #  - env: JOB=IPA

  include:
  # Runs unit tests without emulators.
  - env: JOB=PR
    sudo: false
    language: node_js
    node_js:
      - "stable"
    cache:
      directories:
        - node_modules
    install:
      - npm install

    script:
      - npm run lint
